Repository dawn-ico/dusk, pull requests merged in 2020-10, with the labels that each got.

#52 Removed buggy sparse fill testcase
  tests/stencils/test_sparse_fill.py
Labels: bug

#47 Minor cleanups
  README.md
  dusk/cli.py
  dusk/errors.py
  dusk/grammar.py
  dusk/match.py
  tests/stencils/test_fields.py
Labels: bug, tech debt/maintenance

#48 Simple Vertical Index Fields
  dusk/grammar.py
  dusk/script/__init__.py
  dusk/semantics.py
  tests/examples/test_examples.py
  tests/stencils/test_copy.py
  tests/stencils/test_fields.py
  tests/stencils/test_math.py
  tests/stencils/test_reduce.py
  tests/stencils/test_simple.py
  tests/stencils/test_sparse_fill.py
  tests/stencils/test_vertical_index_fields.py
  tests/test_util.py
Labels: feature, high-prio

#49 Refactor Dusk CLI
  .gitignore
  README.md
  dusk/cli.py
  dusk/front.py
  dusk/transpile.py
  setup.cfg
  tests/stencils/test_math.py
Labels: feature
